export enum HttpErrorType {
  DNS_LOOKUP_ERROR = 'DNS_LOOKUP_ERROR',
  TCP_CONNECTION_ERROR = 'TCP_CONNECTION_ERROR',
  TLS_HANDSHAKE_ERROR = 'TLS_HANDSHAKE_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  REQUEST_ABORTED = 'REQUEST_ABORTED',
  SOCKET_ERROR = 'SOCKET_ERROR',
  RESPONSE_ERROR = 'RESPONSE_ERROR',
  CERT_ERROR = 'CERT_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
