stages:
  - install
  - test
  - e2e

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  NODE_ENV: test

  REDIS_HOST: localhost
  REDIS_PORT: 6379

  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: mydatabase

  JWT_SECRET: jwt-secret
  JWT_EXPIRATION: 1d

  REDIS_URL: redis://localhost:6379
  KAFKA_URL: localhost:9092

################################################
# Install dependencies
################################################

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

################################################
# Unit tests (Docker infra required)
################################################
unit_tests:
  stage: test
  image: docker:24

  services:
    - name: docker:24-dind
      command: ["--tls=false"]

  before_script:
    - apk add --no-cache nodejs npm docker-compose
    - npm ci

  script:
    - export KAFKA_ADVERTISED_HOST_NAME=docker
    - docker-compose up -d
    - sleep 15

    - export POSTGRES_HOST=docker
    - export REDIS_HOST=docker
    - export REDIS_URL=redis://docker:6379
    - export KAFKA_BROKERS=docker:9092
    - export KAFKA_URL=docker:9092
    - export PGHOST=docker

    - npm run test:unit:ci

  after_script:
    - docker-compose down

################################################
# End-to-End tests
################################################

e2e_tests:
  stage: e2e
  image: docker:24

  services:
    - name: docker:24-dind
      command: ["--tls=false"]

  before_script:
    - apk add --no-cache nodejs npm docker-compose
    - npm ci

  script:
    - docker-compose up -d
    - sleep 15

    - export POSTGRES_HOST=docker
    - export REDIS_HOST=docker
    - export REDIS_URL=redis://docker:6379
    - export KAFKA_URL=docker:9092
    - export PGHOST=docker

    - npm run test:e2e:ci

  after_script:
    - docker-compose down

  artifacts:
    when: always
    reports:
      junit: reports/jest-junit.xml
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage/cobertura-coverage.xml
    paths:
      - reports/coverage/